// auth
export const OPEN_AUTH_MODAL_TO_SIGNIN = 'OPEN_AUTH_MODAL_TO_SIGNIN';
export const OPEN_AUTH_MODAL_TO_SIGNUP = 'OPEN_AUTH_MODAL_TO_SIGNUP';
export const CLOSE_AUTH_MODAL = 'CLOSE_AUTH_MODAL';
export const AUTH = 'AUTH';
export const SIGN_OUT = 'SIGN_OUT';

// pagination
export const COUNT_ITEMS_ON_PAGE = 10;
export const COUNT_PAGES_IN_PAGINATION = 5;

// general
export const HANDLE_SPINNER = 'HANDLE_SPINNER';
export const GET_INTL_MESSAGES = 'GET_INTL_MESSAGES';

// places
export const GET_PLACES = 'GET_PLACES';
export const ADD_PLACE = 'ADD_PLACE';
export const EDIT_PLACE = 'EDIT_PLACE';
export const REMOVE_PLACE = 'REMOVE_PLACE';
export const HANDLE_MODAL_ADD_PLACE = 'HANDLE_MODAL_ADD_PLACE';
export const HANDLE_MODAL_EDIT_PLACE = 'HANDLE_MODAL_EDIT_PLACE';
export const HANDLE_MODAL_REMOVE_PLACE = 'HANDLE_MODAL_REMOVE_PLACE';

// clients
export const GET_CLIENTS = 'GET_CLIENTS';
export const ADD_CLIENT = 'ADD_CLIENT';
export const EDIT_CLIENT = 'EDIT_CLIENT';
export const REMOVE_CLIENT = 'REMOVE_CLIENT';
export const HANDLE_MODAL_ADD_CLIENT = 'HANDLE_MODAL_ADD_CLIENT';
export const HANDLE_MODAL_EDIT_CLIENT = 'HANDLE_MODAL_EDIT_CLIENT';
export const HANDLE_MODAL_REMOVE_CLIENT = 'HANDLE_MODAL_REMOVE_CLIENT';

// workers
export const GET_WORKERS = 'GET_WORKERS';
export const ADD_WORKER = 'ADD_WORKER';
export const EDIT_WORKER = 'EDIT_WORKER';
export const REMOVE_WORKER = 'REMOVE_WORKER';
export const HANDLE_MODAL_ADD_WORKER = 'HANDLE_MODAL_ADD_WORKER';
export const HANDLE_MODAL_EDIT_WORKER = 'HANDLE_MODAL_EDIT_WORKER';
export const HANDLE_MODAL_REMOVE_WORKER = 'HANDLE_MODAL_REMOVE_WORKER';

// jobs
export const GET_JOBS = 'GET_JOBS';
export const ADD_JOB = 'ADD_JOB';
export const EDIT_JOB = 'EDIT_JOB';
export const REMOVE_JOB = 'REMOVE_JOB';
export const HANDLE_MODAL_ADD_JOB = 'HANDLE_MODAL_ADD_JOB';
export const HANDLE_MODAL_EDIT_JOB = 'HANDLE_MODAL_EDIT_JOB';
export const HANDLE_MODAL_REMOVE_JOB = 'HANDLE_MODAL_REMOVE_JOB';

// costs
export const GET_COSTS = 'GET_COSTS';
export const ADD_COST = 'ADD_COST';
export const EDIT_COST = 'EDIT_COST';
export const REMOVE_COST = 'REMOVE_COST';
export const HANDLE_MODAL_ADD_COST = 'HANDLE_MODAL_ADD_COST';
export const HANDLE_MODAL_EDIT_COST = 'HANDLE_MODAL_EDIT_COST';
export const HANDLE_MODAL_REMOVE_COST = 'HANDLE_MODAL_REMOVE_COST';
export const HANDLE_MODAL_SELECT_COST = 'HANDLE_MODAL_SELECT_COST';
export const SELECT_COST = 'SELECT_COST';