export default {
    en:
    {
        "costs" : "Costs",
        "workers" : "Workers",
        "jobs" : "Jobs",
        "places" : "Places",
        "searchPlace" : "Search place",
        "sign_in" : "Sign In",
        "sign_out" : "Sign Out",
        "sign_up" : "Sign Up",
        "email" : "Email",
        "warning" : "Warning!",
        "validEmail" : "Email should be valid.",
        "password" : "Password",
        "emptyPassword" : "Password can not be empty.",
        "confirmPass" : "Password confirmation",
        "wrongConfirmPass" : "Confirmation is wrong.",
        "ok" : "Ok",
        "add" : "Add",
        "cancel" : "Cancel",
        "addPlace" : "Add place",
        "editPlace" : "Edit place",
        "name" : "Name",
        "clients" : "Clients",
        "description" : "Description",
        "client" : "Client",
        "address" : "Address",
        "date" : "Date",
        "deleteItem" : "Do you really want do remove the ",
        "remove" : "Remove",
        "placeSML" : "place",
        "addClient" : "Add client",
        "searchClient" : "Search client",
        "editClient" : "Edit client",
        "clientSML" : "client",
        "addWorker" : "Add worker",
        "searchWorker" : "Search worker",
        "editWorker" : "Edit worker",
        "workerSML" : "worker"
    },
    ru:
    {
        "costs" : "Расходы",
        "workers" : "Работники",
        "jobs" : "Виды работ",
        "places" : "Объекты",
        "searchPlace" : "Поиск объекта",
        "sign_in" : "Войти",
        "sign_out" : "Выйти",
        "sign_up" : "Зарегистрироваться",
        "email" : "Email",
        "warning" : "Предупреждение!",
        "validEmail" : "Email должен быть корретным.",
        "password" : "Пароль",
        "emptyPassword" : "Пароль не может быть пустым.",
        "confirmPass" : "Подтверждение пароля",
        "wrongConfirmPass" : "Неверное подтверждение.",
        "ok" : "Ok",
        "add" : "Добавить",
        "cancel" : "Отмена",
        "addPlace" : "Добавить объект",
        "editPlace" : "Редактировать объект",
        "name" : "Имя",
        "clients" : "Заказчики",
        "description" : "Описание",
        "client" : "Заказчик",
        "address" : "Адрес",
        "date" : "Дата",
        "deleteItem" : "Вы действительно хотите удалить ",
        "remove" : "Удалить",
        "placeSML" : "объект",
        "addClient" : "Добавить заказчика",
        "searchClient" : "Поиск заказчика",
        "editClient" : "Редактировать заказчика",
        "clientSML" : "заказчика",
        "addWorker" : "Добавить работника",
        "searchWorker" : "Поиск работника",
        "editWorker" : "Редактировать работника",
        "workerSML" : "работника"
    }
}